### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by mcadamsrails** [jsturdevant/golf-league#28]
I keep getting this error: The username or password you entered is invalid. Be sure the account is activated. I have tried using the default admin that is int he MySQL database that comes with the project. I also tried creating a new admin user. Either way, I can not log in. Everything else got installed correctly.

**Comment by jsturdevant** [comment]
Just to be sure I'm looking at the same thing you are - are you using the vm with Vagrant?

**Comment by mcadamsrails** [comment]
I dropped all the tables and re-inserted them, now it's working. Thanks for the quick response. I can delete question if you'd like.
